import type { LucideIcon } from 'lucide-react'
import {
  LayoutDashboard,
  Users,
  FileText,
  Tv,
  Wallet,
  FileSignature,
  FolderOpen,
  MessageCircle,
  Database,
  Workflow,
  BarChart3,
  Settings,
  Gauge,
  Bell,
  ClipboardCheck,
  Clock,
  Activity,
  PenLine,
  UserRound,
  Handshake,
  Globe,
  Languages,
  Headphones,
  Radio,
  Building2,
  Files,
  Plug,
  Copy,
  CalendarDays,
  CalendarRange,
  Archive,
  MonitorPlay,
  Calendar,
  RefreshCw,
  BellRing,
  Landmark,
  Store,
  Banknote,
  CheckCircle2,
  History,
  FileBarChart,
  Signature,
  UserCheck,
  FolderArchive,
  Contact,
  BookUser,
  Home,
  KeyRound,
  MessageSquare,
  HelpCircle,
  Bot,
  UserCog,
  LayoutTemplate,
  FileSpreadsheet,
  ClipboardList,
  ShieldCheck,
  ScrollText,
  Download,
  CircleDollarSign,
  FileDown,
  CreditCard,
  Cog,
} from 'lucide-react'

export interface SubSection {
  label: string
  icon: LucideIcon
}

export interface Section {
  id: string
  path: string
  label: string
  description: string
  icon: LucideIcon
  subSections: SubSection[]
}

export const sections: Section[] = [
  {
    id: 'dashboard',
    path: '/',
    label: 'Dashboard',
    description: 'نظرة عامة على مؤشرات المنصة والتنبيهات وآخر العمليات.',
    icon: LayoutDashboard,
    subSections: [
      { label: 'Overview', icon: Gauge },
      { label: 'Notifications', icon: Bell },
      { label: 'Pending Matching', icon: ClipboardCheck },
      { label: 'Pending Payments', icon: Clock },
      { label: 'Statistics', icon: BarChart3 },
      { label: 'Activity Timeline', icon: Activity },
    ],
  },
  {
    id: 'beneficiaries',
    path: '/beneficiaries',
    label: 'Beneficiaries',
    description: 'إدارة فئات المستفيدين وبياناتهم.',
    icon: Users,
    subSections: [
      { label: 'Writers', icon: PenLine },
      { label: 'Guests', icon: UserRound },
      { label: 'Contributors', icon: Handshake },
      { label: 'Website Contributors', icon: Globe },
      { label: 'Translators', icon: Languages },
      { label: 'Live Translators', icon: Headphones },
      { label: 'Reporters', icon: Radio },
      { label: 'TV Employees', icon: Tv },
      { label: 'Government Employees', icon: Building2 },
    ],
  },
  {
    id: 'editorial',
    path: '/editorial',
    label: 'Editorial',
    description: 'متابعة المواد المكتوبة وتصنيفها وأرشفتها.',
    icon: FileText,
    subSections: [
      { label: 'Articles', icon: Files },
      { label: 'Syria TV API', icon: Plug },
      { label: 'Website Contributors', icon: Globe },
      { label: 'Duplicate Detection', icon: Copy },
      { label: 'Monthly Matching', icon: CalendarDays },
      { label: 'Quarterly Matching', icon: CalendarRange },
      { label: 'Archive', icon: Archive },
    ],
  },
  {
    id: 'tv-appearances',
    path: '/tv-appearances',
    label: 'TV Appearances',
    description: 'متابعة ظهورات المستفيدين على الشاشة والبرامج.',
    icon: Tv,
    subSections: [
      { label: 'All Appearances', icon: Tv },
      { label: 'Writers', icon: PenLine },
      { label: 'Guests', icon: UserRound },
      { label: 'Contributors', icon: Handshake },
      { label: 'Website Contributors', icon: Globe },
      { label: 'Reporters', icon: Radio },
      { label: 'Programs', icon: MonitorPlay },
      { label: 'Calendar', icon: Calendar },
      { label: 'Monthly View', icon: CalendarDays },
      { label: 'Quarterly View', icon: CalendarRange },
      { label: 'Archive', icon: Archive },
    ],
  },
  {
    id: 'finance',
    path: '/finance',
    label: 'Finance',
    description: 'إدارة التحويلات والإشعارات وبيانات الصرف.',
    icon: Wallet,
    subSections: [
      { label: 'Payment Cycles', icon: RefreshCw },
      { label: 'Transfer Notices', icon: BellRing },
      { label: 'Bank Transfers', icon: Landmark },
      { label: 'Exchange Offices', icon: Store },
      { label: 'Cash Studio', icon: Banknote },
      { label: 'ShamCash (Coming Soon)', icon: Wallet },
      { label: 'Settlement', icon: CheckCircle2 },
      { label: 'Payment History', icon: History },
      { label: 'Reports', icon: FileBarChart },
    ],
  },
  {
    id: 'contracts',
    path: '/contracts',
    label: 'Contracts',
    description: 'العقود والتواقيع الرسمية.',
    icon: FileSignature,
    subSections: [
      { label: 'Financial Agreement', icon: FileText },
      { label: 'Electronic Signature', icon: Signature },
      { label: 'Delegation', icon: UserCheck },
      { label: 'Agreement Archive', icon: FolderArchive },
    ],
  },
  {
    id: 'documents',
    path: '/documents',
    label: 'Documents',
    description: 'الوثائق الثبوتية للمستفيدين وأرشفتها.',
    icon: FolderOpen,
    subSections: [
      { label: 'National ID', icon: Contact },
      { label: 'Passport', icon: BookUser },
      { label: 'Proof of Residence', icon: Home },
      { label: 'Beneficiary Documents', icon: Files },
      { label: 'Archive', icon: Archive },
    ],
  },
  {
    id: 'whatsapp',
    path: '/whatsapp',
    label: 'WhatsApp Center',
    description: 'إدارة قنوات واتساب والرسائل والردود الآلية.',
    icon: MessageCircle,
    subSections: [
      { label: 'WhatsApp API #1', icon: MessageCircle },
      { label: 'WhatsApp API #2', icon: MessageCircle },
      { label: 'OTP Verification', icon: KeyRound },
      { label: 'Matching Messages', icon: MessageSquare },
      { label: 'Transfer Notifications', icon: BellRing },
      { label: 'FAQ', icon: HelpCircle },
      { label: 'AI Assistant', icon: Bot },
      { label: 'Human Agent', icon: UserCog },
      { label: 'Templates', icon: LayoutTemplate },
    ],
  },
  {
    id: 'data-center',
    path: '/data-center',
    label: 'Data Center',
    description: 'مصادر البيانات والمزامنة والتدقيق.',
    icon: Database,
    subSections: [
      { label: 'Syria TV API', icon: Tv },
      { label: 'LK API', icon: Plug },
      { label: 'Excel Import', icon: FileSpreadsheet },
      { label: 'Beneficiary Master Record', icon: ClipboardList },
      { label: 'Article Import', icon: FileText },
      { label: 'TV Appearance Import', icon: Tv },
      { label: 'Duplicate Engine', icon: Copy },
      { label: 'Validation Engine', icon: ShieldCheck },
      { label: 'Archive Engine', icon: Archive },
      { label: 'Audit Log', icon: ScrollText },
      { label: 'Synchronization', icon: RefreshCw },
    ],
  },
  {
    id: 'workflow-engine',
    path: '/workflow-engine',
    label: 'Workflow Engine',
    description: 'مراحل سير العمل من الاستيراد حتى إغلاق التسوية.',
    icon: Workflow,
    subSections: [
      { label: 'Import', icon: Download },
      { label: 'Verification', icon: ShieldCheck },
      { label: 'Financial Verification', icon: CircleDollarSign },
      { label: 'Agreement', icon: FileSignature },
      { label: 'Monthly Matching', icon: CalendarDays },
      { label: 'Quarterly Matching', icon: CalendarRange },
      { label: 'Payment', icon: Banknote },
      { label: 'Transfer Notice', icon: BellRing },
      { label: 'Beneficiary Confirmation', icon: UserCheck },
      { label: 'Close Settlement', icon: CheckCircle2 },
    ],
  },
  {
    id: 'reports',
    path: '/reports',
    label: 'Reports',
    description: 'تقارير وإحصاءات قابلة للتصدير.',
    icon: BarChart3,
    subSections: [
      { label: 'Monthly Reports', icon: CalendarDays },
      { label: 'Quarterly Reports', icon: CalendarRange },
      { label: 'Beneficiary Reports', icon: Users },
      { label: 'Editorial Reports', icon: FileText },
      { label: 'Finance Reports', icon: FileBarChart },
      { label: 'Export Excel', icon: FileSpreadsheet },
      { label: 'Export PDF', icon: FileDown },
    ],
  },
  {
    id: 'settings',
    path: '/settings',
    label: 'Settings',
    description: 'إعدادات النظام والمستخدمين والصلاحيات.',
    icon: Settings,
    subSections: [
      { label: 'Users', icon: Users },
      { label: 'Roles & Permissions', icon: ShieldCheck },
      { label: 'Payment Settings', icon: CreditCard },
      { label: 'WhatsApp Settings', icon: MessageCircle },
      { label: 'API Settings', icon: Plug },
      { label: 'Archive Settings', icon: Archive },
      { label: 'System Configuration', icon: Cog },
    ],
  },
]

export function getSection(path: string): Section {
  const section = sections.find((s) => s.path === path)
  if (!section) {
    throw new Error(`Unknown section path: ${path}`)
  }
  return section
}
