import type { LucideIcon } from 'lucide-react'
import {
  LayoutDashboard,
  Users,
  FileText,
  Tv,
  ClipboardCheck,
  Wallet,
  FileSignature,
  MessageCircle,
  Database,
  BarChart3,
  Settings,
  Gauge,
  Bell,
  ArrowLeftRight,
  Clock,
  PenLine,
  UserRound,
  Handshake,
  Globe,
  Languages,
  Headphones,
  Radio,
  Building2,
  Files,
  Copy,
  Archive,
  MonitorPlay,
  Calendar,
  CalendarDays,
  CalendarRange,
  AlertCircle,
  CheckCircle2,
  BellRing,
  Store,
  Landmark,
  Banknote,
  Signature,
  UserCheck,
  Contact,
  BookUser,
  FolderArchive,
  KeyRound,
  MessageSquare,
  HelpCircle,
  Bot,
  UserCog,
  Plug,
  FileSpreadsheet,
  ScrollText,
  RefreshCw,
  ShieldCheck,
  LayoutTemplate,
  CreditCard,
  FileBarChart,
} from 'lucide-react'

export interface SubSection {
  label: string
  icon: LucideIcon
}

export interface Section {
  id: string
  path: string
  label: string
  description: string
  icon: LucideIcon
  subSections: SubSection[]
}

export const sections: Section[] = [
  {
    id: 'dashboard',
    path: '/',
    label: 'Dashboard',
    description: 'نظرة عامة على مؤشرات المنصة والتنبيهات وآخر العمليات.',
    icon: LayoutDashboard,
    subSections: [
      { label: 'مؤشرات عامة', icon: Gauge },
      { label: 'تنبيهات', icon: Bell },
      { label: 'آخر المطابقات', icon: ClipboardCheck },
      { label: 'آخر التحويلات', icon: ArrowLeftRight },
      { label: 'حالات بانتظار المراجعة', icon: Clock },
    ],
  },
  {
    id: 'beneficiaries',
    path: '/beneficiaries',
    label: 'المستفيدون',
    description: 'إدارة فئات المستفيدين وبياناتهم.',
    icon: Users,
    subSections: [
      { label: 'كاتب', icon: PenLine },
      { label: 'ضيف', icon: UserRound },
      { label: 'متعاون', icon: Handshake },
      { label: 'متعاون موقع', icon: Globe },
      { label: 'مترجم', icon: Languages },
      { label: 'مترجم فوري', icon: Headphones },
      { label: 'مراسل', icon: Radio },
      { label: 'موظف تلفزيون', icon: Tv },
      { label: 'موظف حكومي', icon: Building2 },
    ],
  },
  {
    id: 'editorial',
    path: '/editorial',
    label: 'الاستكتاب',
    description: 'متابعة المواد المكتوبة وتصنيفها وأرشفتها.',
    icon: FileText,
    subSections: [
      { label: 'جميع المواد', icon: Files },
      { label: 'مواد الكتاب', icon: PenLine },
      { label: 'مواد الضيوف', icon: UserRound },
      { label: 'مواد المتعاونين', icon: Handshake },
      { label: 'مواد متعاون الموقع', icon: Globe },
      { label: 'المواد المكررة', icon: Copy },
      { label: 'الأرشيف', icon: Archive },
    ],
  },
  {
    id: 'tv-appearances',
    path: '/tv-appearances',
    label: 'الظهور التلفزيوني',
    description: 'متابعة ظهورات المستفيدين على الشاشة والبرامج.',
    icon: Tv,
    subSections: [
      { label: 'جميع الظهورات', icon: Tv },
      { label: 'ظهور الضيوف', icon: UserRound },
      { label: 'ظهور الكتاب', icon: PenLine },
      { label: 'ظهور المتعاونين', icon: Handshake },
      { label: 'ظهور متعاون الموقع', icon: Globe },
      { label: 'ظهور المراسلين', icon: Radio },
      { label: 'البرامج', icon: MonitorPlay },
      { label: 'فلترة حسب التاريخ', icon: Calendar },
      { label: 'فلترة حسب الشهر', icon: CalendarDays },
      { label: 'فلترة حسب الربع السنوي', icon: CalendarRange },
    ],
  },
  {
    id: 'reconciliation',
    path: '/reconciliation',
    label: 'المطابقات',
    description: 'مطابقة الاستحقاقات ومتابعة الردود والملاحظات.',
    icon: ClipboardCheck,
    subSections: [
      { label: 'مطابقة شهرية', icon: CalendarDays },
      { label: 'مطابقة الاستكتاب', icon: FileText },
      { label: 'مطابقة الظهور التلفزيوني', icon: Tv },
      { label: 'مطابقة ربع سنوية', icon: CalendarRange },
      { label: 'بانتظار رد المستفيد', icon: Clock },
      { label: 'ملاحظات ونواقص', icon: AlertCircle },
      { label: 'مطابقات مغلقة', icon: CheckCircle2 },
    ],
  },
  {
    id: 'finance',
    path: '/finance',
    label: 'المالية',
    description: 'إدارة التحويلات والإشعارات وبيانات الصرف.',
    icon: Wallet,
    subSections: [
      { label: 'كشف التحويلات', icon: ArrowLeftRight },
      { label: 'إشعارات التحويل', icon: BellRing },
      { label: 'بيانات الصراف', icon: Store },
      { label: 'التحويل البنكي / IBAN', icon: Landmark },
      { label: 'Cash Studio', icon: Banknote },
      { label: 'ShamCash - قريباً - Admin Only', icon: Wallet },
      { label: 'التسويات المغلقة', icon: CheckCircle2 },
    ],
  },
  {
    id: 'contracts',
    path: '/contracts',
    label: 'العقود والوثائق',
    description: 'العقود والوثائق والتواقيع الرسمية.',
    icon: FileSignature,
    subSections: [
      { label: 'العقد المالي', icon: FileText },
      { label: 'التوقيع الإلكتروني', icon: Signature },
      { label: 'التفويض', icon: UserCheck },
      { label: 'الهوية', icon: Contact },
      { label: 'الجواز', icon: BookUser },
      { label: 'أرشيف الوثائق', icon: FolderArchive },
    ],
  },
  {
    id: 'whatsapp',
    path: '/whatsapp',
    label: 'WhatsApp Center',
    description: 'إدارة قنوات واتساب والرسائل والردود الآلية.',
    icon: MessageCircle,
    subSections: [
      { label: 'WhatsApp API 1', icon: MessageCircle },
      { label: 'WhatsApp API 2', icon: MessageCircle },
      { label: 'OTP', icon: KeyRound },
      { label: 'رسائل المطابقة', icon: MessageSquare },
      { label: 'إشعارات التحويل', icon: BellRing },
      { label: 'الأسئلة الشائعة', icon: HelpCircle },
      { label: 'الردود الآلية', icon: Bot },
      { label: 'تحويل لموظف', icon: UserCog },
    ],
  },
  {
    id: 'data-center',
    path: '/data-center',
    label: 'Data Center',
    description: 'مصادر البيانات والمزامنة والتدقيق.',
    icon: Database,
    subSections: [
      { label: 'Syria TV API', icon: Tv },
      { label: 'LK API', icon: Plug },
      { label: 'Excel Import', icon: FileSpreadsheet },
      { label: 'Duplicate Checker', icon: Copy },
      { label: 'Archive Engine', icon: Archive },
      { label: 'Audit Log', icon: ScrollText },
      { label: 'Sync Status', icon: RefreshCw },
    ],
  },
  {
    id: 'reports',
    path: '/reports',
    label: 'التقارير',
    description: 'تقارير وإحصاءات قابلة للتصدير.',
    icon: BarChart3,
    subSections: [
      { label: 'تقارير شهرية', icon: CalendarDays },
      { label: 'تقارير ربع سنوية', icon: CalendarRange },
      { label: 'تصدير Excel', icon: FileSpreadsheet },
      { label: 'تصدير PDF', icon: FileText },
      { label: 'إحصائيات المستفيدين', icon: Users },
      { label: 'إحصائيات المواد', icon: FileBarChart },
      { label: 'إحصائيات الظهور', icon: BarChart3 },
    ],
  },
  {
    id: 'settings',
    path: '/settings',
    label: 'الإعدادات',
    description: 'إعدادات النظام والمستخدمين والصلاحيات.',
    icon: Settings,
    subSections: [
      { label: 'المستخدمون', icon: Users },
      { label: 'الصلاحيات', icon: ShieldCheck },
      { label: 'القوالب', icon: LayoutTemplate },
      { label: 'إعدادات واتساب', icon: MessageCircle },
      { label: 'إعدادات الدفع', icon: CreditCard },
      { label: 'إعدادات الأرشفة', icon: Archive },
    ],
  },
]

export function getSection(path: string): Section {
  const section = sections.find((s) => s.path === path)
  if (!section) {
    throw new Error(`Unknown section path: ${path}`)
  }
  return section
}
